apiVersion: apps/v1
kind: Deployment
metadata:
  name: freezebio-django-deployment
  namespace: default
  labels:
    app: freezebio-django
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      MaxUnavailable: 0
  selector:
    matchLabels:
      app: freezebio-django
  template:
    metadata:
      labels:
        app: hitman-rest-api
      # annotations:
    spec:
      terminationGracePeriodSeconds: 300
      imagePullSecrets:
        -name: dockerconfigjson-github-com
      containers:
        - name: freezebio-django-docker-image
          image: 
          imagePullPolicy: IfNotPresent
          resources:
            requests:
            cpu: "250m"
            memory: "100M"
          limits:
            cpu: "500m"
            memory: "100M"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /admin/login/?next=/admin/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
          livenessProble:
            httpGet:
              path: /admin/login/?next=/admin/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 120


























