apiVersion: apps/v1
kind: Deployment
metadata:
  name: freezebio-django-deployment
  namespace: default
  labels:
    app: freezebio-django
spec:
  replicas: 2
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0
  selector:
    matchLabels:
      app: freezebio-django
  template:
    metadata:
      labels:
        app: freezebio-django
      # annotations:
    spec:
      # terminationGracePeriodSeconds: 300
      # imagePullSecrets:
        # -name: dockerconfigjson-github-com
      containers:
        - name: freezebio-django-docker-image
          image: madhan248/freezebio:freezebiolatest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "250m"
              memory: "100M"
            limits:
              cpu: "500m"
              memory: "100M"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /admin/login/?next=/admin/
              port: 8000
            initialDelaySeconds: 200
            periodSeconds: 200
          livenessProbe:
            httpGet:
              path: /admin/login/?next=/admin/
              port: 8000
            initialDelaySeconds: 200
            periodSeconds: 200

---
apiVersion: v1
kind: Service
metadata:
  name: freezebio-django-load-balancer
spec:
  selector:
    app: freezebio-django
  ports:
    - port: 80
      name: http
      targetPort: 8000
    - port: 443
      name: https
      targetPort: 8000
  type: LoadBalancer