# Generated by Django 4.2 on 2023-05-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('timestamp', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('service', models.CharField(blank=True, default='', max_length=150, null=True)),
            ],
        ),
    ]
